name: 自动部署

# 当有改动推送到main分支时，启动Action

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with: 
          ref: main
      
      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      
      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
      
      - name: 缓存 Hexo
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: 安装依赖
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install --save
          npm i yamljs --save
      
      - name: 生成静态文件
        run: |
          hexo clean
          node link.js
          hexo generate
      
      - name: 部署到public分支
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: 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
          repository-name: Lbb886/Daily
          branch: public
          folder: public
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"

      - name: 部署到Github pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: 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
          repository-name: Lbb886/Lbb886.github.io
          branch: main
          folder: public
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"
